export const WIZARD_ACTIONS = {
  UPDATE_STEPS_CONFIG: "UPDATE_STEPS_CONFIG",
  UPDATE_ACTIVE_STEP_INDEX: "UPDATE_ACTIVE_STEP_INDEX",
  UPDATE_STORED_DATA: "UPDATE_STORED_DATA",
  UPDATE_INVALID_STEPS: "UPDATE_INVALID_STEPS",
  RESET_STEPS_CONFIG: "RESET_STEPS_CONFIG",
} as const;